### ISSUE TITLE
Remove obsolete code and env vars related to Digital Ocean

### ISSUE THREAD

**Issue by eecavanna** [microbiomedata/nmdc-runtime#512]
#### Tasks

- [ ] Remove code specific to Digital Ocean (can move to long-lived branch if want to preserve)
- [ ] Remove environment variables specific to Digital Ocean
- [ ] Delete those environment variables from deployments (@eecavanna can help with this on Rancher, given the list of environment variables)

#### Examples

This is not an exhaustive list (although I think it's close).

https://github.com/microbiomedata/nmdc-runtime/blob/fb9131649f0d6ab70e7b1f105b569837afa63d17/nmdc_runtime/api/db/s3.py#L15-L18

https://github.com/microbiomedata/nmdc-runtime/blob/fb9131649f0d6ab70e7b1f105b569837afa63d17/.env.example#L9-L12

**Comment by PeopleMakeCulture** [comment]
@eecavanna the [workflow execution demo notebook](https://github.com/microbiomedata/nmdc-runtime/blob/736d349073cdf7a661293a557f617916733ea836/metadata-translation/notebooks/202106_workflow_execution_demo.ipynb) uses `DO_*` env vars.
```python
@lru_cache
def get_s3_client():
    _session = boto3.session.Session()
    return _session.client(
        "s3",
        region_name=os.getenv("DO_REGION_NAME"),
        endpoint_url=os.getenv("DO_ENDPOINT_URL"),
        aws_access_key_id=os.getenv("DO_SPACES_KEY"),
        aws_secret_access_key=os.getenv("DO_SPACES_SECRET"),
    )
```
Going to leave them in for now, until we can confirm that the notebook is updated or no longer in use.

**Comment by eecavanna** [comment]
Thanks, @PeopleMakeCulture. I agree about leaving those environment variable references there until we have confirmed whether the notebook is still in use or not.

I'd prefer this ticket remain open in the meantime. I'm going to reopen it before tomorrow's hackathon, as I think it fits tomorrow's hackathon topic well (it has to do with eliminating obsolete code). I'll also add the "backlog" label to it. In case this approach doesn't fit well with how the Polyneme board is managed, you can edit the assignee list (e.g. assign it to me or to nobody), remove it from the Polyneme board, etc.

**Comment by shreddd** [comment]
@eecavanna - please confirm if this is done and close

**Comment by eecavanna** [comment]
It is not done. There are still references to these `DO_*` environment variables in the codebase.

https://github.com/microbiomedata/nmdc-runtime/blob/89c7d03912d5f8aa16282e4988f382479893a7bf/nmdc_runtime/api/db/s3.py#L10-L19

Hi @dwinston, are you familiar with the Runtime's relationship with Digital Ocean? Maybe this Digital Ocean-related code is a remnant of a past experiment, similar to how TerminusDB was a remnant of a past experiment and we were able to [clean it up](https://github.com/microbiomedata/nmdc-runtime/pull/542) from the repo, environment variables, and development stack.

**Comment by dwinston** [comment]
Yes, it's a remnant of a past experiment, to facilitate managed object storage via Runtime API e.g. via `POST /sites/{site_id}:putObject`. In practice, only HPC filesystems have been used for large-file/blob storage, runtime-external workflow code manages filesystem access directly, and all `GET` access for these files is done via "public" http proxy via the `url` field of `nmdc:DataObject` entities. All runtime-internal "file" management (e.g. persistence of changesheets and submitted json) is done using MongoDB GridFS rather than S3-compatible object storage (e.g. through Digital Ocean). So, we might as well retire all the Digital Ocean and S3-related stuff.

**Comment by eecavanna** [comment]
Thanks, @dwinston, for confirming the Digital Ocean-related code is a remnant of a past experiment, and for including that additional context. I'll move this forward by a couple sprints as I do not expect to have bandwidth to address it next sprint.
