### ISSUE TITLE
Remove obsolete code, env vars, container related to TerminusDB

### ISSUE THREAD

**Issue by eecavanna** [microbiomedata/nmdc-runtime#513]
#### Tasks

- [x] Remove code specific to [TerminusDB](https://terminusdb.com/) (can move to long-lived branch if want to preserve)
- [x] Remove environment variables specific to TerminusDB
- [ ] Delete those environment variables from deployments (@eecavanna can help with this on Rancher, given the list of environment variables)
- [ ] Remove `terminus` service ("container") from development stack

#### Examples

This is not an exhaustive list.

https://github.com/microbiomedata/nmdc-runtime/blob/fb9131649f0d6ab70e7b1f105b569837afa63d17/nmdc_runtime/api/db/terminus.py#L10

https://github.com/microbiomedata/nmdc-runtime/blob/fb9131649f0d6ab70e7b1f105b569837afa63d17/nmdc_runtime/site/graphs.py#L91

https://github.com/microbiomedata/nmdc-runtime/blob/fb9131649f0d6ab70e7b1f105b569837afa63d17/nmdc_runtime/site/resources.py#L517

https://github.com/microbiomedata/nmdc-runtime/blob/fb9131649f0d6ab70e7b1f105b569837afa63d17/terminusdb#L3

https://github.com/microbiomedata/nmdc-runtime/blob/fb9131649f0d6ab70e7b1f105b569837afa63d17/nmdc_runtime/site/terminusdb/generate.py#L84

https://github.com/microbiomedata/nmdc-runtime/blob/fb9131649f0d6ab70e7b1f105b569837afa63d17/nmdc_runtime/site/terminusdb/.TDB#L1

https://github.com/microbiomedata/nmdc-runtime/blob/fb9131649f0d6ab70e7b1f105b569837afa63d17/nmdc_runtime/site/entrypoint-dagit.sh#L24

https://github.com/microbiomedata/nmdc-runtime/blob/fb9131649f0d6ab70e7b1f105b569837afa63d17/docker-compose.yml#L91-L104

etc.

Suggestion: Use GitHub's search feature to search the repo for `TERMINUS`.

**Comment by PeopleMakeCulture** [comment]
Blocked by https://github.com/microbiomedata/nmdc-runtime/issues/468
