### ISSUE TITLE
Standardize tracking of Berkeley Schema Roll Out tasks (either use meta issue or Milestone)

### ISSUE THREAD

**Issue by eecavanna** [microbiomedata/nmdc-runtime#659]
### Tasks

- [x] 1. Synchronize the list of issues between the meta issue and the milestone
- [x] 2. Eliminate one or the other
- [ ] 3. Advertise my expectations on Slack

**Comment by eecavanna** [comment]
Also, **group** the issues by what's in the Runtime application, versus what just happens to live in the same repo.

**Comment by eecavanna** [comment]
I moved all issues that only existed in the Milestone, into the meta issue; and then I deleted the Milestone. I will use the meta issue moving forward.
